services:
  postgres:
    image: postgres:15-alpine
    container_name: insurance-postgres
    environment:
      POSTGRES_DB: insurance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - insurance-network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: insurance-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"      # AMQP port
      - "15672:15672"    # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - insurance-network
    restart: unless-stopped

  mockserver:
    image: mockserver/mockserver:5.15.0
    container_name: insurance-mockserver
    ports:
      - "1080:1080"
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
    volumes:
      - ./mockserver:/config
    networks:
      - insurance-network
    restart: unless-stopped

  app:
    build: .
    container_name: insurance-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/insurance_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_RABBITMQ_HOST: rabbitmq
      FRAUD_API_URL: http://mockserver:1080/api/fraud-analysis
    depends_on:
      - postgres
      - rabbitmq
      - mockserver
    networks:
      - insurance-network

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  insurance-network:
    driver: bridge 